plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'jacoco'
    id 'org.openapi.generator' version '7.10.0'
}

group = 'ru.clevertec'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

ext {
    springBootVersion = '3.4.1'
    dependencyManagementVersion = '1.1.7'
    openApiGeneratorVersion = '7.10.0'
    springCloudVersion = '2024.0.0'
    mapStructVersion = '1.4.2.Final'
    lombokVersion = '1.18.36'
    gsonVersion = '2.11.0'
    gsonFireVersion = '1.9.0'
    okhttpVersion = '4.12.0'
    jacksonNullableVersion = '0.2.6'
    javaxAnnotationVersion = '1.3.2'
    springdocVersion = '2.8.1'
    jsonwebtokenVersion = '0.12.6'
    redisVersion = '3.4.1'
    jakartaVersion = '3.1.0'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'jacoco'
    apply plugin: 'org.openapi.generator'

    group = 'ru.clevertec'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenLocal()
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    dependencies {
        runtimeOnly "io.jsonwebtoken:jjwt-impl:${jsonwebtokenVersion}"
        runtimeOnly "io.jsonwebtoken:jjwt-jackson:${jsonwebtokenVersion}"

        compileOnly "org.projectlombok:lombok:${lombokVersion}"
        annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
        annotationProcessor "org.mapstruct:mapstruct-processor:${mapStructVersion}"

        implementation "jakarta.validation:jakarta.validation-api:${jakartaVersion}"
        implementation "org.springframework.boot:spring-boot-starter-data-redis:${redisVersion}"
        implementation "org.mapstruct:mapstruct:${mapStructVersion}"
        implementation 'org.springframework.boot:spring-boot-starter-web'
        implementation 'ru.clevertec:logger-starter:1.0'
        implementation 'ru.clevertec:exception-starter:1.0'
        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
        implementation "org.openapitools:jackson-databind-nullable:${jacksonNullableVersion}"
        implementation "javax.annotation:javax.annotation-api:${javaxAnnotationVersion}"
        implementation "com.google.code.gson:gson:${gsonVersion}"
        implementation "com.squareup.okhttp3:logging-interceptor:${okhttpVersion}"
        implementation "io.gsonfire:gson-fire:${gsonFireVersion}"
        implementation "org.springdoc:springdoc-openapi-starter-common:${springdocVersion}"
        implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"
        implementation "io.jsonwebtoken:jjwt-api:${jsonwebtokenVersion}"
        implementation 'org.hibernate.validator:hibernate-validator-annotation-processor:9.0.0.CR1'
        implementation 'org.hibernate.validator:hibernate-validator:9.0.0.CR1'

        testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
        testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"


        testImplementation 'org.springframework.boot:spring-boot-starter-test'
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('bootJar') {
    mainClass.set("ru.clevertec.CommentsServiceApplication")
}
