services:
  app:
    build:
      context: .
    container_name: comments_service
    ports:
      - "8082:8082"
    depends_on:
      - db-news
    restart: always
  db-news:
    image: postgres:15
    environment:
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: news_pass
      POSTGRES_DB: COMMENTS_PLATFORM
    ports:
      - "5434:5432"