spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5434/COMMENTS_PLATFORM
    username: news_user
    password: news_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true